openapi: 3.0.3
info:
  version: 1.0.0
  title: Calc API
  description: Calc api for truenorth challenge

servers:
  - description: The server for the API
    url: https://nezqwerft9.execute-api.us-east-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: api/v1

paths:
  /users:
    post:
      summary: Creates a New User
      parameters:
        - name: X-Api-Key
          schema:
            type: string
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      requestBody:
        content:
          "application/vnd.api+json":
            schema:
              $ref: "#/components/schemas/UserRequest"
        description: "User to Add to the system"
      responses:
        201:
          description: Created
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/UserCreated"
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /users/tokens:
    post:
      summary: Creates a new Access Token for authenticated requests.
      parameters:
        - name: X-Api-Key
          schema:
            type: string
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      requestBody:
        required: true
        content:
           "application/vnd.api+json":
             schema:
               $ref: "#/components/schemas/UserRequest"
      responses:
        201:
          description: Success
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        400:
          description: Bad Request
        401:
          description: Unauthorized

  /operations/types:
    get:
      summary: Retrieves a list of valid operations.
      security:
        - JWT: []
      parameters:
        - name: X-Api-Key
          schema:
            type: string
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      responses:
        200:
          description: Success
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/OperationsSuccess"
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /operations:
    post:
      summary: Perform a new Operation.
      security:
        - JWT: [ ]
      parameters:
        - name: X-Api-Key
          schema:
            type: string
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      requestBody:
        content:
          "application/vnd.api+json":
            schema:
              $ref: "#/components/schemas/CreateOperation"
      responses:
        201:
          description: Created
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/OperationResult"
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        400:
          description: Bad Request

  /records:
    get:
      summary: Get List of Records
      security:
        - JWT: []
      parameters:
        - name: X-Api-Key
          schema:
            type: string
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      responses:
        200:
          description: Success
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/RecordResult"


components:
  schemas:
    RecordResult:
      type: object
      properties:
        data:
          type: array
          required:
            - data
          items:
            type: object
            properties:
              type:
                type: string
              id:
                type: string
              attributes:
                type: object
                properties:
                  operation_id:
                    type: integer
                  user_id:
                    type: string

                  amount:
                    type: integer

                  user_balance:
                    type: integer
                  operation_response:
                    oneOf:
                      - type: integer
                      - type: string
                  date:
                    type: string
    OperationResult:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: string
            attributes:
              type: object
              properties:
                operation_id:
                  type: integer
                user_id:
                  type: string
                amount:
                  type: integer
                user_balance:
                  type: integer
                operation_response:
                  oneOf:
                    - type: integer
                    - type: string
                date:
                  type: string
    CreateOperation:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            attributes:
              type: object
              properties:
                operation_id:
                  type: integer
                operands:
                  type: array
                  minItems: 1
                  maxItems: 2
                  items:
                    type: integer
    UserRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
    UserCreated:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: string
            attributes:
              type: object
              properties:
                username:
                  type: string
                status:
                  type: string
    LoginSuccess:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: string
            attributes:
              type: object
              properties:
                access_token:
                  type: string
                expires_in:
                  type: integer
    OperationsSuccess:
      type: object
      properties:
        data:
          type: array
          items:
            properties:
              type:
                type: string
              id:
                type: integer
              attributes:
                type: object
                properties:
                  type:
                    type: string
                  cost:
                    type: integer

  securitySchemes:
    JWT:
      type: http
      bearerFormat: Bearer
      description: Access token provided by POST /users/tokens
      scheme: bearer