openapi: 3.0.3
info:
  version: 1.0.0
  title: Calc API
  description: Calc api for truenorth challenge

servers:
  - description: The server for the API
    url: https://pbqnjc55c3.execute-api.us-east-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: api/v1

paths:
  /users:
    post:
      summary: Creates a New User
      parameters:
        - name: X-Api-Key
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      requestBody:
        content:
          "application/vnd.api+json":
            schema:
              $ref: "#/components/schemas/UserRequest"
        description: "User to Add to the system"
      responses:
        201:
          description: Created
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/UserCreated"
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /users/tokens:
    post:
      summary: Creates a new Access Token for authenticated requests.
      parameters:
        - name: X-Api-Key
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      requestBody:
        required: true
        content:
           "application/vnd.api+json":
             schema:
               $ref: "#/components/schemas/UserRequest"
      responses:
        201:
          description: Success
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        400:
          description: Bad Request
        401:
          description: Unauthorized

  /operations:
    get:
      summary: Retrieves a list of valid operations.
      security:
        - JWT: []
      parameters:
        - name: X-Api-Key
          in: header
          description: Api Key provided in order to integrate Apps
          required: true
      responses:
        200:
          description: Success
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/OperationsSuccess"
        401:
          description: Unauthorized
        403:
          description: Forbidden



components:
  schemas:
    UserRequest:
      type: object
      properties:
        data:
          type: object
          required: true
          properties:
            username:
              type: string
              required: true
            password:
              type: string
              required: true
    UserCreated:
      type: object
      properties:
        data:
          type: object
          required: true
          properties:
            type:
              type: string
              required: true
            id:
              type: string
              required: true
            attributes:
              type: object
              required: true
              properties:
                username:
                  type: string
                  required: true
                status:
                  type: string
                  required: true
    LoginSuccess:
      type: object
      properties:
        data:
          type: object
          required: true
          properties:
            type:
              type: string
              required: true
            id:
              type: string
              required: true
            attributes:
              type: object
              required: true
              properties:
                access_token:
                  type: string
                  required: true
                expires_in:
                  type: integer
                  required: true
    OperationsSuccess:
      type: object
      properties:
        data:
          type: array
          required: true
          items:
            properties:
              type:
                type: string
              id:
                type:
                  string
              attributes:
                type: object
                properties:
                  type:
                    type: string
                  cost:
                    type: integer


  securitySchemes:
    JWT:
      type: http
      bearerFormat: bearer
      description: Access token provided by POST /users/tokens
      scheme: Bearer