service: truenorth-calc-api

frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  wsgi:
    app: src/functions/app.app

package:
  exclude:
    - tests
    - docs

provider:
  name: aws
  runtime: python3.9

  environment:
    USERS_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
#        - Effect: Allow
#          Action:
#            - dynamodb:Query
#            - dynamodb:Scan
#            - dynamodb:GetItem
#            - dynamodb:PutItem
#            - dynamodb:UpdateItem
#            - dynamodb:DeleteItem
#          Resource:
#            - Fn::GetAtt: [ UsersTable, Arn ]
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
#            - cognito-idp:AdminCreateUser
#            - cognito-idp:AdminSetUserPassword
          Resource: "*"
functions:
  api:
    handler: wsgi_handler.handler
    environment:
      user_pool_id: { Ref: CognitoUserPoolCalcUserPool }
      client_id: { Ref: CalcUserClient }
      FLASK_ENV: development
      API_VERSION: 1
    dependsOn:
      - CognitoUserPoolCalcUserPool
    events:
      - httpApi: '*'

  preSignup:
    handler: src/functions/pre_sign_up.pre_sign_up
    events:
      - cognitoUserPool:
          pool: CalcUserPool
          trigger: PreSignUp
plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    CognitoUserPoolCalcUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-calc-user-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        UsernameAttributes: [email]
        AutoVerifiedAttributes:
          - email

    CalcUserClient:
      DependsOn: CognitoUserPoolCalcUserPool
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: serverless-calc-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: CognitoUserPoolCalcUserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"

#  extensions:
#    CognitoUserPoolCalcUserPool:
#      Prop
#    ApiLambdaFunction:
#      DependsOn: CalcUserClient
#    PreSignupLambdaFunction:
#      DependsOn: CalcUserClient
#    UsersTable:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        AttributeDefinitions:
#          - AttributeName: userId
#            AttributeType: S
#        KeySchema:
#          - AttributeName: userId
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#          WriteCapacityUnits: 1
#        TableName: ${self:custom.tableName}



