service: truenorth-calc-api

frameworkVersion: '3'

custom:
  calcTableName: 'CalcTable-${sls:stage}'
  wsgi:
    app: src/functions/app.app

package:
  exclude:
    - tests
    - docs
useDotenv: true
provider:
  name: aws
  runtime: python3.9
  environment:
    CALC_TABLE: ${self:custom.calcTableName}
    APP_STAGE: ${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - Fn::GetAtt: [ CalcTable, Arn ]
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
          Resource: "*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${env:SECRET_ARN}
functions:
  api:
    handler: wsgi_handler.handler
    environment:
      user_pool_id: { Ref: CognitoUserPoolCalcUserPool }
      client_id: { Ref: CalcUserClient }
      FLASK_ENV: development
      API_VERSION: 1
    dependsOn:
      - CognitoUserPoolCalcUserPool
    events:
      - httpApi: '*'

  preSignup:
    handler: src/functions/pre_sign_up.pre_sign_up
    events:
      - cognitoUserPool:
          pool: CalcUserPool
          trigger: PreSignUp
  setUpDatabase:
    handler: src/functions/set_up_database.set_up_database

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    CognitoUserPoolCalcUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-calc-user-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        UsernameAttributes: [email]
        AutoVerifiedAttributes:
          - email

    CalcUserClient:
      DependsOn: CognitoUserPoolCalcUserPool
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: serverless-calc-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: CognitoUserPoolCalcUserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"
    CalcTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ClassName
            AttributeType: S
          - AttributeName: OpId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: RecordId
            AttributeType: S
        KeySchema:
          - AttributeName: ClassName
            KeyType: HASH
          - AttributeName: RecordId
            KeyType: RANGE
        TableName: ${self:custom.calcTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - IndexName: ClassNameUserId
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: ClassName
                KeyType: HASH
              - AttributeName: UserId
                KeyType: RANGE
          - IndexName: ClassNameOpId
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: ClassName
                KeyType: HASH
              - AttributeName: OpId
                KeyType: RANGE




